sequenceDiagram
    autonumber
    participant Caller as caller
    participant DealResource
    Note over Caller,DealResource: 2026-08-04 21:53:32.559 - 21:53:32.567<br/>8.04 ms | thread executor-thread-3
    Caller->>DealResource: create(DealDto)
    activate DealResource
    DealResource--xCaller: throws ResteasyReactiveViolationException [8.04 ms]
    deactivate DealResource
