sequenceDiagram
    autonumber
    participant Caller as caller
    participant SessionService
    Note over Caller,SessionService: 2026-08-04 21:53:30.771 - 21:53:30.775<br/>4.00 ms | thread executor-thread-1
    Caller->>SessionService: authenticate(String)
    activate SessionService
    SessionService-->>Caller: AppUser [4.00 ms]
    deactivate SessionService
