sequenceDiagram
    autonumber
    participant Caller as caller
    participant SessionAuthenticationMechanism
    Note over Caller,SessionAuthenticationMechanism: 2026-08-04 21:53:30.159 - 21:53:30.159<br/>0.15 ms | thread vert.x-eventloop-thread-6
    Caller->>SessionAuthenticationMechanism: sendChallenge(RoutingContext)
    activate SessionAuthenticationMechanism
        SessionAuthenticationMechanism->>SessionAuthenticationMechanism: getChallenge(RoutingContext)
        activate SessionAuthenticationMechanism
        SessionAuthenticationMechanism-->>SessionAuthenticationMechanism: Uni [0.06 ms]
        deactivate SessionAuthenticationMechanism
    SessionAuthenticationMechanism-->>Caller: Uni [0.15 ms]
    deactivate SessionAuthenticationMechanism
