sequenceDiagram
    autonumber
    participant Caller as caller
    participant CurrentUser
    Note over Caller,CurrentUser: 2026-08-04 21:51:18.251 - 21:51:18.252<br/>1.53 ms | thread executor-thread-1
    Caller->>CurrentUser: find()
    activate CurrentUser
    CurrentUser-->>Caller: Optional [1.53 ms]
    deactivate CurrentUser
