sequenceDiagram
    autonumber
    participant Caller as caller
    participant SessionAuthenticationMechanism
    Note over Caller,SessionAuthenticationMechanism: 2026-08-04 21:51:17.636 - 21:51:17.636<br/>0.14 ms | thread vert.x-eventloop-thread-1
    Caller->>SessionAuthenticationMechanism: sendChallenge(RoutingContext)
    activate SessionAuthenticationMechanism
        SessionAuthenticationMechanism->>SessionAuthenticationMechanism: getChallenge(RoutingContext)
        activate SessionAuthenticationMechanism
        SessionAuthenticationMechanism-->>SessionAuthenticationMechanism: Uni [0.06 ms]
        deactivate SessionAuthenticationMechanism
    SessionAuthenticationMechanism-->>Caller: Uni [0.14 ms]
    deactivate SessionAuthenticationMechanism
