sequenceDiagram
    autonumber
    participant Caller as caller
    participant ApiExceptionMappers
    Note over Caller,ApiExceptionMappers: 2026-08-04 21:53:02.835 - 21:53:02.836<br/>0.12 ms | thread executor-thread-3
    Caller->>ApiExceptionMappers: handleConstraintViolation(ConstraintViolationException)
    activate ApiExceptionMappers
    ApiExceptionMappers-->>Caller: Response [0.12 ms]
    deactivate ApiExceptionMappers
