sequenceDiagram
    autonumber
    participant Caller as caller
    participant ContactResource
    Note over Caller,ContactResource: 2026-08-04 21:53:02.826 - 21:53:02.835<br/>8.16 ms | thread executor-thread-3
    Caller->>ContactResource: create(ContactDto)
    activate ContactResource
    ContactResource--xCaller: throws ResteasyReactiveViolationException [8.16 ms]
    deactivate ContactResource
