sequenceDiagram
    autonumber
    participant Caller as caller
    participant AuthResource
    participant UserService
    participant CurrentUser
    Note over Caller,CurrentUser: 2026-08-04 21:53:06.766 - 21:53:06.767<br/>0.89 ms | thread executor-thread-1
    Caller->>AuthResource: me()
    activate AuthResource
        AuthResource->>UserService: me()
        activate UserService
            UserService->>CurrentUser: get()
            activate CurrentUser
                CurrentUser->>CurrentUser: find()
                activate CurrentUser
                CurrentUser-->>CurrentUser: Optional [0.30 ms]
                deactivate CurrentUser
            CurrentUser-->>UserService: AppUser [0.39 ms]
            deactivate CurrentUser
        UserService-->>AuthResource: UserDto [0.47 ms]
        deactivate UserService
    AuthResource-->>Caller: UserDto [0.89 ms]
    deactivate AuthResource
