sequenceDiagram
    autonumber
    participant Caller as caller
    participant AutoBackupTrigger
    Note over Caller,AutoBackupTrigger: 2026-08-04 21:53:08.535 - 21:53:08.535<br/>0.15 ms | thread executor-thread-3
    Caller->>AutoBackupTrigger: dataChanged()
    activate AutoBackupTrigger
    AutoBackupTrigger-->>Caller: void [0.15 ms]
    deactivate AutoBackupTrigger
