sequenceDiagram
    autonumber
    participant Caller as caller
    participant CurrentUser
    Note over Caller,CurrentUser: 2026-08-04 21:51:02.099 - 21:51:02.101<br/>1.44 ms | thread executor-thread-1
    Caller->>CurrentUser: find()
    activate CurrentUser
    CurrentUser-->>Caller: Optional [1.44 ms]
    deactivate CurrentUser
