sequenceDiagram
    autonumber
    participant Caller as caller
    participant SessionService
    Note over Caller,SessionService: 2026-08-04 21:51:02.093 - 21:51:02.097<br/>3.51 ms | thread executor-thread-1
    Caller->>SessionService: authenticate(String)
    activate SessionService
    SessionService-->>Caller: AppUser [3.51 ms]
    deactivate SessionService
