sequenceDiagram
    autonumber
    participant Caller as caller
    participant SessionAuthenticationMechanism
    participant SessionCookie
    Note over Caller,SessionCookie: 2026-08-04 21:51:01.041 - 21:51:01.042<br/>0.90 ms | thread vert.x-eventloop-thread-2
    Caller->>SessionAuthenticationMechanism: authenticate(RoutingContext, IdentityProviderManager)
    activate SessionAuthenticationMechanism
        SessionAuthenticationMechanism->>SessionCookie: read(RoutingContext)
        activate SessionCookie
        SessionCookie-->>SessionAuthenticationMechanism: String [0.14 ms]
        deactivate SessionCookie
    SessionAuthenticationMechanism-->>Caller: Uni [0.90 ms]
    deactivate SessionAuthenticationMechanism
