sequenceDiagram
    autonumber
    participant Caller as caller
    participant AppointmentResource
    participant AppointmentService
    Note over Caller,AppointmentService: 2026-08-04 21:52:29.848 - 21:52:29.850<br/>1.43 ms | thread executor-thread-3
    Caller->>AppointmentResource: list(Instant, Instant)
    activate AppointmentResource
        AppointmentResource->>AppointmentService: list(Instant, Instant)
        activate AppointmentService
        AppointmentService-->>AppointmentResource: List [1.42 ms]
        deactivate AppointmentService
    AppointmentResource-->>Caller: List [1.43 ms]
    deactivate AppointmentResource
