sequenceDiagram
    autonumber
    participant Caller as caller
    participant AppointmentResource
    participant AppointmentService
    participant CurrentUser
    Note over Caller,CurrentUser: 2026-08-04 21:52:30.277 - 21:52:30.282<br/>5.77 ms | thread executor-thread-3
    Caller->>AppointmentResource: conflicts(Instant, Instant, Long)
    activate AppointmentResource
        AppointmentResource->>AppointmentService: conflicts(Long, Instant, Instant)
        activate AppointmentService
            AppointmentService->>CurrentUser: find()
            activate CurrentUser
            CurrentUser-->>AppointmentService: Optional [0.33 ms]
            deactivate CurrentUser
        AppointmentService-->>AppointmentResource: List [5.74 ms]
        deactivate AppointmentService
    AppointmentResource-->>Caller: List [5.77 ms]
    deactivate AppointmentResource
