sequenceDiagram
    autonumber
    participant Caller as caller
    participant AppointmentResource
    participant AppointmentService
    participant CurrentUser
    participant ReferenceResolver
    Note over Caller,ReferenceResolver: 2026-08-04 21:52:31.780 - 21:52:31.786<br/>5.27 ms | thread executor-thread-3
    Caller->>AppointmentResource: create(AppointmentDto, boolean)
    activate AppointmentResource
        AppointmentResource->>AppointmentService: create(AppointmentDto, boolean)
        activate AppointmentService
            AppointmentService->>CurrentUser: find()
            activate CurrentUser
            CurrentUser-->>AppointmentService: Optional [0.55 ms]
            deactivate CurrentUser
            AppointmentService->>ReferenceResolver: contact(Long)
            activate ReferenceResolver
            ReferenceResolver-->>AppointmentService: Contact [0.00 ms]
            deactivate ReferenceResolver
            AppointmentService->>ReferenceResolver: deal(Long)
            activate ReferenceResolver
            ReferenceResolver-->>AppointmentService: Deal [0.00 ms]
            deactivate ReferenceResolver
        AppointmentService--xAppointmentResource: throws AppointmentConflictException [2.10 ms]
        deactivate AppointmentService
    AppointmentResource--xCaller: throws AppointmentConflictException [5.27 ms]
    deactivate AppointmentResource
