sequenceDiagram
    autonumber
    participant Caller as caller
    participant SessionAuthenticationMechanism
    Note over Caller,SessionAuthenticationMechanism: 2026-08-04 21:52:27.606 - 21:52:27.606<br/>0.16 ms | thread vert.x-eventloop-thread-4
    Caller->>SessionAuthenticationMechanism: sendChallenge(RoutingContext)
    activate SessionAuthenticationMechanism
        SessionAuthenticationMechanism->>SessionAuthenticationMechanism: getChallenge(RoutingContext)
        activate SessionAuthenticationMechanism
        SessionAuthenticationMechanism-->>SessionAuthenticationMechanism: Uni [0.07 ms]
        deactivate SessionAuthenticationMechanism
    SessionAuthenticationMechanism-->>Caller: Uni [0.16 ms]
    deactivate SessionAuthenticationMechanism
