sequenceDiagram
    autonumber
    participant Caller as caller
    participant AutoBackupTrigger
    Note over Caller,AutoBackupTrigger: 2026-08-04 21:52:57.128 - 21:52:57.128<br/>0.24 ms | thread executor-thread-1
    Caller->>AutoBackupTrigger: dataChanged()
    activate AutoBackupTrigger
    AutoBackupTrigger-->>Caller: void [0.24 ms]
    deactivate AutoBackupTrigger
