sequenceDiagram
    autonumber
    participant Caller as caller
    participant SessionAuthenticationMechanism
    Note over Caller,SessionAuthenticationMechanism: 2026-08-04 21:52:55.377 - 21:52:55.377<br/>0.20 ms | thread executor-thread-1
    Caller->>SessionAuthenticationMechanism: getCredentialTransport(RoutingContext)
    activate SessionAuthenticationMechanism
    SessionAuthenticationMechanism-->>Caller: Uni [0.20 ms]
    deactivate SessionAuthenticationMechanism
