sequenceDiagram
    autonumber
    participant Caller as caller
    participant SessionService
    Note over Caller,SessionService: 2026-08-04 21:52:55.373 - 21:52:55.376<br/>3.49 ms | thread executor-thread-1
    Caller->>SessionService: authenticate(String)
    activate SessionService
    SessionService-->>Caller: AppUser [3.49 ms]
    deactivate SessionService
