sequenceDiagram
    autonumber
    participant Caller as caller
    participant CompanyResource
    participant CompanyService
    participant CurrentUser
    Note over Caller,CurrentUser: 2026-08-04 21:52:17.092 - 21:52:17.095<br/>2.51 ms | thread executor-thread-1
    Caller->>CompanyResource: create(CompanyDto)
    activate CompanyResource
        CompanyResource->>CompanyService: create(CompanyDto)
        activate CompanyService
            CompanyService->>CurrentUser: find()
            activate CurrentUser
            CurrentUser-->>CompanyService: Optional [0.47 ms]
            deactivate CurrentUser
        CompanyService-->>CompanyResource: CompanyDto [1.28 ms]
        deactivate CompanyService
    CompanyResource-->>Caller: Response [2.51 ms]
    deactivate CompanyResource
