sequenceDiagram
    autonumber
    participant Caller as caller
    participant CrmTaskResource
    participant CrmTaskService
    Note over Caller,CrmTaskService: 2026-08-04 21:53:38.005 - 21:53:38.007<br/>1.57 ms | thread executor-thread-5
    Caller->>CrmTaskResource: setDone(Long, boolean)
    activate CrmTaskResource
        CrmTaskResource->>CrmTaskService: setDone(Long, boolean)
        activate CrmTaskService
        CrmTaskService-->>CrmTaskResource: CrmTaskDto [0.72 ms]
        deactivate CrmTaskService
    CrmTaskResource-->>Caller: CrmTaskDto [1.57 ms]
    deactivate CrmTaskResource
