sequenceDiagram
    autonumber
    participant Caller as caller
    participant SessionService
    Note over Caller,SessionService: 2026-08-04 21:54:13.718 - 21:54:13.722<br/>3.53 ms | thread executor-thread-1
    Caller->>SessionService: authenticate(String)
    activate SessionService
    SessionService-->>Caller: AppUser [3.53 ms]
    deactivate SessionService
