sequenceDiagram
    autonumber
    participant Caller as caller
    participant SessionAuthenticationMechanism
    Note over Caller,SessionAuthenticationMechanism: 2026-08-04 21:52:48.118 - 21:52:48.118<br/>0.18 ms | thread vert.x-eventloop-thread-4
    Caller->>SessionAuthenticationMechanism: sendChallenge(RoutingContext)
    activate SessionAuthenticationMechanism
        SessionAuthenticationMechanism->>SessionAuthenticationMechanism: getChallenge(RoutingContext)
        activate SessionAuthenticationMechanism
        SessionAuthenticationMechanism-->>SessionAuthenticationMechanism: Uni [0.09 ms]
        deactivate SessionAuthenticationMechanism
    SessionAuthenticationMechanism-->>Caller: Uni [0.18 ms]
    deactivate SessionAuthenticationMechanism
