sequenceDiagram
    autonumber
    participant Caller as caller
    participant BootstrapAdminService
    Note over Caller,BootstrapAdminService: 2026-08-04 21:51:10.792 - 21:51:11.157<br/>365.0 ms | thread main
    Caller->>BootstrapAdminService: createAdminIfNoUsersExist()
    activate BootstrapAdminService
    BootstrapAdminService-->>Caller: AppUser [365.0 ms]
    deactivate BootstrapAdminService
