sequenceDiagram
    autonumber
    participant Caller as caller
    participant SessionService
    Note over Caller,SessionService: 2026-08-04 21:52:43.124 - 21:52:43.128<br/>3.86 ms | thread executor-thread-1
    Caller->>SessionService: authenticate(String)
    activate SessionService
    SessionService-->>Caller: AppUser [3.86 ms]
    deactivate SessionService
