sequenceDiagram
    autonumber
    participant Caller as caller
    participant SessionAuthenticationMechanism
    participant SessionCookie
    Note over Caller,SessionCookie: 2026-08-04 21:52:42.081 - 21:52:42.082<br/>0.77 ms | thread vert.x-eventloop-thread-2
    Caller->>SessionAuthenticationMechanism: authenticate(RoutingContext, IdentityProviderManager)
    activate SessionAuthenticationMechanism
        SessionAuthenticationMechanism->>SessionCookie: read(RoutingContext)
        activate SessionCookie
        SessionCookie-->>SessionAuthenticationMechanism: String [0.13 ms]
        deactivate SessionCookie
    SessionAuthenticationMechanism-->>Caller: Uni [0.77 ms]
    deactivate SessionAuthenticationMechanism
