sequenceDiagram
    autonumber
    participant Caller as caller
    participant BackupResource
    participant BackupService
    Note over Caller,BackupService: 2026-08-04 21:52:11.192 - 21:52:11.193<br/>0.25 ms | thread executor-thread-1
    Caller->>BackupResource: list()
    activate BackupResource
        BackupResource->>BackupService: list()
        activate BackupService
            BackupService->>BackupService: directory()
            activate BackupService
            BackupService-->>BackupService: Path [0.01 ms]
            deactivate BackupService
        BackupService-->>BackupResource: List [0.03 ms]
        deactivate BackupService
    BackupResource-->>Caller: List [0.25 ms]
    deactivate BackupResource
