sequenceDiagram
    autonumber
    participant Caller as caller
    participant BootstrapAdminService
    Note over Caller,BootstrapAdminService: 2026-08-04 21:52:07.951 - 21:52:08.299<br/>347.9 ms | thread main
    Caller->>BootstrapAdminService: createAdminIfNoUsersExist()
    activate BootstrapAdminService
    BootstrapAdminService-->>Caller: AppUser [347.9 ms]
    deactivate BootstrapAdminService
