sequenceDiagram
    autonumber
    participant Caller as caller
    participant ApiExceptionMappers
    Note over Caller,ApiExceptionMappers: 2026-08-04 21:53:56.729 - 21:53:56.729<br/>0.11 ms | thread executor-thread-4
    Caller->>ApiExceptionMappers: handleConstraintViolation(ConstraintViolationException)
    activate ApiExceptionMappers
    ApiExceptionMappers-->>Caller: Response [0.11 ms]
    deactivate ApiExceptionMappers
