sequenceDiagram
    autonumber
    participant Caller as caller
    participant DealResource
    Note over Caller,DealResource: 2026-08-04 21:53:56.721 - 21:53:56.728<br/>6.98 ms | thread executor-thread-4
    Caller->>DealResource: create(DealDto)
    activate DealResource
    DealResource--xCaller: throws ResteasyReactiveViolationException [6.98 ms]
    deactivate DealResource
