sequenceDiagram
    autonumber
    participant Caller as caller
    participant SessionAuthenticationMechanism
    Note over Caller,SessionAuthenticationMechanism: 2026-08-04 21:54:21.010 - 21:54:21.010<br/>0.19 ms | thread executor-thread-1
    Caller->>SessionAuthenticationMechanism: getCredentialTransport(RoutingContext)
    activate SessionAuthenticationMechanism
    SessionAuthenticationMechanism-->>Caller: Uni [0.19 ms]
    deactivate SessionAuthenticationMechanism
