sequenceDiagram
    autonumber
    participant Caller as caller
    participant ApiExceptionMappers
    Note over Caller,ApiExceptionMappers: 2026-08-04 21:54:10.117 - 21:54:10.117<br/>0.18 ms | thread executor-thread-3
    Caller->>ApiExceptionMappers: handleConstraintViolation(ConstraintViolationException)
    activate ApiExceptionMappers
    ApiExceptionMappers-->>Caller: Response [0.18 ms]
    deactivate ApiExceptionMappers
