sequenceDiagram
    autonumber
    participant Caller as caller
    participant BootstrapAdminService
    Note over Caller,BootstrapAdminService: 2026-08-04 21:54:06.619 - 21:54:06.965<br/>346.0 ms | thread main
    Caller->>BootstrapAdminService: createAdminIfNoUsersExist()
    activate BootstrapAdminService
    BootstrapAdminService-->>Caller: AppUser [346.0 ms]
    deactivate BootstrapAdminService
