-- Copyright 2026 the Small CRM authors.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- The starting schema of Small CRM.
--
-- Installations that predate Flyway already carry this schema, created by Hibernate; they are
-- baselined at version 1 and skip this script. Everything after this point is an ordinary
-- versioned migration.

CREATE TABLE app_user (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           VARCHAR(100)             NOT NULL,
    password           VARCHAR(200)             NOT NULL,
    roles              VARCHAR(100)             NOT NULL,
    fullName           VARCHAR(150),
    email              VARCHAR(200),
    mustChangePassword BOOLEAN                  NOT NULL,
    active             BOOLEAN                  NOT NULL,
    createdAt          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_app_user_username UNIQUE (username)
);

CREATE TABLE company (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200)                NOT NULL,
    vatId      VARCHAR(50),
    website    VARCHAR(200),
    email      VARCHAR(200),
    phone      VARCHAR(50),
    street     VARCHAR(200),
    postalCode VARCHAR(20),
    city       VARCHAR(100),
    country    VARCHAR(100),
    notes      VARCHAR(4000),
    owner_id   BIGINT,
    version    BIGINT                      NOT NULL,
    createdAt  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updatedAt  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_company_owner FOREIGN KEY (owner_id) REFERENCES app_user (id)
);

CREATE TABLE contact (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName  VARCHAR(100)                NOT NULL,
    lastName   VARCHAR(100)                NOT NULL,
    email      VARCHAR(200),
    phone      VARCHAR(50),
    mobile     VARCHAR(50),
    position   VARCHAR(150),
    company_id BIGINT,
    notes      VARCHAR(4000),
    owner_id   BIGINT,
    version    BIGINT                      NOT NULL,
    createdAt  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updatedAt  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_contact_company FOREIGN KEY (company_id) REFERENCES company (id),
    CONSTRAINT fk_contact_owner FOREIGN KEY (owner_id) REFERENCES app_user (id)
);

-- Tag collection of a contact. The unique constraint is what makes it a set rather than a bag.
CREATE TABLE contact_tag (
    contact_id BIGINT NOT NULL,
    tag        VARCHAR(50),
    CONSTRAINT fk_contact_tag_contact FOREIGN KEY (contact_id) REFERENCES contact (id),
    CONSTRAINT uk_contact_tag UNIQUE (contact_id, tag)
);

CREATE TABLE deal (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(200)                NOT NULL,
    contact_id        BIGINT,
    company_id        BIGINT,
    -- Named "amount" because VALUE is a reserved word in H2.
    amount            NUMERIC(15, 2),
    currency          VARCHAR(3)                  NOT NULL,
    stage             VARCHAR(20)                 NOT NULL,
    expectedCloseDate DATE,
    notes             VARCHAR(4000),
    owner_id          BIGINT,
    version           BIGINT                      NOT NULL,
    createdAt         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updatedAt         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_deal_contact FOREIGN KEY (contact_id) REFERENCES contact (id),
    CONSTRAINT fk_deal_company FOREIGN KEY (company_id) REFERENCES company (id),
    CONSTRAINT fk_deal_owner FOREIGN KEY (owner_id) REFERENCES app_user (id)
);

CREATE TABLE interaction (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type       VARCHAR(20)                 NOT NULL,
    occurredAt TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    subject    VARCHAR(200)                NOT NULL,
    notes      VARCHAR(4000),
    contact_id BIGINT                      NOT NULL,
    deal_id    BIGINT,
    owner_id   BIGINT,
    version    BIGINT                      NOT NULL,
    createdAt  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updatedAt  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_interaction_contact FOREIGN KEY (contact_id) REFERENCES contact (id),
    CONSTRAINT fk_interaction_deal FOREIGN KEY (deal_id) REFERENCES deal (id),
    CONSTRAINT fk_interaction_owner FOREIGN KEY (owner_id) REFERENCES app_user (id)
);

CREATE TABLE crm_task (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200)                NOT NULL,
    description VARCHAR(4000),
    dueDate     DATE,
    done        BOOLEAN                     NOT NULL,
    completedAt TIMESTAMP(6) WITH TIME ZONE,
    priority    VARCHAR(10)                 NOT NULL,
    contact_id  BIGINT,
    deal_id     BIGINT,
    owner_id    BIGINT,
    version     BIGINT                      NOT NULL,
    createdAt   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updatedAt   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_crm_task_contact FOREIGN KEY (contact_id) REFERENCES contact (id),
    CONSTRAINT fk_crm_task_deal FOREIGN KEY (deal_id) REFERENCES deal (id),
    CONSTRAINT fk_crm_task_owner FOREIGN KEY (owner_id) REFERENCES app_user (id)
);

CREATE TABLE appointment (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(200)                NOT NULL,
    startsAt           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    endsAt             TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    timeZone           VARCHAR(60)                 NOT NULL,
    location           VARCHAR(200),
    notes              VARCHAR(4000),
    contact_id         BIGINT,
    deal_id            BIGINT,
    -- Reserved for the Google Calendar synchronisation described in todo.md, so appointments
    -- entered today can be adopted by it without a further migration.
    externalCalendarId VARCHAR(200),
    externalEventId    VARCHAR(200),
    externalEtag       VARCHAR(200),
    lastSyncedAt       TIMESTAMP(6) WITH TIME ZONE,
    owner_id           BIGINT,
    version            BIGINT                      NOT NULL,
    createdAt          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updatedAt          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_appointment_contact FOREIGN KEY (contact_id) REFERENCES contact (id),
    CONSTRAINT fk_appointment_deal FOREIGN KEY (deal_id) REFERENCES deal (id),
    CONSTRAINT fk_appointment_owner FOREIGN KEY (owner_id) REFERENCES app_user (id)
);

-- Supports the overlap query, which is the hottest read in the calendar.
CREATE INDEX idx_appointment_slot ON appointment (startsAt, endsAt);
