sequenceDiagram
    autonumber
    participant Caller as caller
    participant DealResource
    participant DealService
    Note over Caller,DealService: 2026-08-04 21:53:15.279 - 21:53:15.290<br/>11.2 ms | thread executor-thread-3
    Caller->>DealResource: list(DealStage, boolean, Long, Integer, Integer)
    activate DealResource
        DealResource->>DealService: list(DealStage, boolean, Long, PageRequest)
        activate DealService
        DealService-->>DealResource: Paged [10.4 ms]
        deactivate DealService
    DealResource-->>Caller: Response [11.2 ms]
    deactivate DealResource
