sequenceDiagram
    autonumber
    participant Caller as caller
    participant ApiExceptionMappers
    Note over Caller,ApiExceptionMappers: 2026-08-04 21:52:04.012 - 21:52:04.012<br/>0.09 ms | thread executor-thread-1
    Caller->>ApiExceptionMappers: handleBusinessRule(BusinessRuleException)
    activate ApiExceptionMappers
    ApiExceptionMappers-->>Caller: Response [0.09 ms]
    deactivate ApiExceptionMappers
