sequenceDiagram
    autonumber
    participant Caller as caller
    participant BootstrapAdminService
    Note over Caller,BootstrapAdminService: 2026-08-04 21:51:58.130 - 21:51:58.480<br/>349.7 ms | thread main
    Caller->>BootstrapAdminService: createAdminIfNoUsersExist()
    activate BootstrapAdminService
    BootstrapAdminService-->>Caller: AppUser [349.7 ms]
    deactivate BootstrapAdminService
