sequenceDiagram
    autonumber
    participant Caller as caller
    participant BootstrapAdminService
    Note over Caller,BootstrapAdminService: 2026-08-04 21:54:24.852 - 21:54:25.199<br/>346.4 ms | thread main
    Caller->>BootstrapAdminService: createAdminIfNoUsersExist()
    activate BootstrapAdminService
    BootstrapAdminService-->>Caller: AppUser [346.4 ms]
    deactivate BootstrapAdminService
